title: MinGJ
description: Minimalistic GNU for JavaScript

url: https://tumble1999.github.io/mingj

markdown: kramdown
theme: minima
kramdown:
  math-engine: mathjax
  auto_ids: false
  input: GFM
  entity-output: as_char
  footnote-nr: "1"
  toc-levels: 1..6
  gfm-quirks: paragraph_end
  syntax-highlighter-opts:
    default-lang: plaintext
  syntax-highlighter: rouge
  smart-quotes: lsquo,rsquo,ldquo,rdquo

  excludes:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - "*.sh"
  - README.md
  - gulffile.js
  - package.json
  - vendor
  - .gitignore
  - .gitattributes
  - CNAME
  - icomoon-selection.json
  - src
  - node_modules
  - misc
  - .vscode
  - devices.txt
  - wasm
  - gulpfile.js
  - LICENSE
  - package**.json
  - TODO.md

defaults:
  - scope:
      path: ""
    values:
      layout: default